chore(deploy): add deploy workflow
WalletConnect/cloud-auth-api pull request #3
Opened 2023-04-07 12:23 UTC by Cali93

2023-04-07 15:20 UTC, xav approved these changes
LGTM

2023-04-12 11:19 UTC, HarryET requested changes

2023-04-12 11:19 UTC, HarryET commented on .github/workflows/cd.yaml
> +      - name: Build and push Docker image to Amazon ECR
You can use docker build here, have a look at Echo's deploy here: https://github.com/WalletConnect/echo-server/blob/85b8c485a4645ee231de8662b6875809ab775837/.github/workflows/release.yml#L110-L137

2023-04-12 11:19 UTC, HarryET commented on .github/workflows/cd.yaml
> +          args: |
You can use env vars for the Terraform variables, https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_var_name

2023-04-12 11:19 UTC, HarryET commented on .github/workflows/cd.yaml
> +env:
If these are only used once why not inline them? Also the cluster name and service name, etc aren't needed terraform manages them

2023-04-12 11:19 UTC, HarryET commented on .github/workflows/cd.yaml
> +  DATABASE_URL: ${{ secrets.DATABASE_URL }}
```suggestion
env:
  AWS_REGION: eu-central-1
  CLOUD_APP_ORIGIN: ${{ secrets.CLOUD_APP_ORIGIN }}
  SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
  COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
```

2023-04-12 11:19 UTC, HarryET commented on .github/workflows/cd.yaml
> +env:
Also a couple question what is, `DIRECT_URL` and `DATABASE_URL` refers to the hosted supabase db right?

2023-04-27 10:45 UTC, merged